#!/usr/bin/env python
"""Add a symbol to database"""

from argparse import ArgumentParser
from pathlib import Path
import unicodedata

parser = ArgumentParser(description=__doc__)
parser.add_argument('symbol', help='symbol name')
parser.add_argument(
    '--override', help='override', action='store_true', default=False)
args = parser.parse_args()

symbols = Path(__file__).parent.absolute() / 'fzu' / 'symbols'
fname = symbols / args.symbol
if not args.override and fname.exists():
    raise SystemExit(f'error: {args.symbol!r} already exists')

try:
    sym = unicodedata.lookup(args.symbol)
except KeyError as err:
    raise SystemExit(f'error: {err.message}')

with fname.open('w') as fp:
    fp.write(sym)
